### ISSUE TITLE
Deprecated set-env and add-path

### ISSUE THREAD

**Issue by capra314cabra** [ashutoshvarma/setup-ninja#4]
When I used `setup-ninja`, it crashed with the following errors:

```
Error: Unable to process command '::add-path::ninja_bin' successfully.
Error: The `add-path` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```

Also suggested in the error messages, you can fix this error by just merging #3 for updating `@actions/core` package from 1.2.0 to 1.2.6.
I hope you will consider this.

**Comment by ashutoshvarma** [comment]
Thanks for reporting!
I bumped `@actions/core` to 1.2.6 in the latest release [v1.1](https://github.com/ashutoshvarma/setup-ninja/releases/tag/v1.1).
Let me know if it resolves your issue.

**Comment by capra314cabra** [comment]
Thank you for your prompt reply!
I have confirmed that the latest works correctly on Windows, Ubuntu, and Mac OS.
